services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pos-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/pos_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
    networks:
      - pos-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos-frontend
    ports:
<<<<<<< Updated upstream
      - "80:80"
=======
      - "3000:80"
>>>>>>> Stashed changes
    depends_on:
      - backend
    networks:
      - pos-network

  db:
    image: postgres:13-alpine
    container_name: pos-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge

volumes:
  postgres_data:
